### ISSUE TITLE
schedule view: weird UI artifacts when jumping to bottom times

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#6]
If you are on the schedule view and scroll to the bottom and there are multiple timeslots visible on the screen, then clicking the time quick-scroll options on the right side for any of those times will result in each of them being highlighted.

For example, on an iphone 6:
Go to the schedule for Tuesday.
Click the "5:30" quick-scroll option on the right side. (Note that 4:00 actually gets highlighted, since 4:00, 5:30 and 10:30 sessions are all visible on the screen.)
Click the "5:30" quick-scroll option.  (now 4:00 and 5:30 options are highlighted)
Click the "10:30" quick-scroll option.  (now 4:00, 5:30 and 10:30 are all highlighted).

**Comment by johnmwright** [comment]
![image](https://cloud.githubusercontent.com/assets/3373249/16462611/9d947630-3df7-11e6-9fb7-cb54ac5ad039.png)

**Comment by johnmwright** [comment]
found in v3.0.0.1

**Comment by mdridley** [comment]
Should be fixed in latest version

**Comment by mcookWI** [comment]
This behavior is still occurring in app version 4.1.3.0, running on an iPhone 7 Plus, iOS version 12.3.1. See below for the steps I followed:

1. Go to Monday’s schedule (Aug 05)
2. Click the 6:00 quick-scroll option on the bottom right side (Note: the quick-scroll actually highlights 1:00, since 1:00, 3:00 and 6:00 sessions are all visible on the screen)
3. Click the 3:00 quick-scroll option (now 1:00 and 3:00 are highlighted)
4. Click the 6:00 quick-scroll option (now 1:00, 3:00 and 6:00 are all highlighted)

![IMG_3041](https://user-images.githubusercontent.com/5367626/60632851-87942400-9dcd-11e9-966f-ce15c1817c5a.png)
